---
title: Обработка ошибок ввода-вывода в .NET
ms.date: 08/27/2018
ms.technology: dotnet-standard
dev_langs:
- csharp
- vb
helpviewer_keywords:
- I/O, exception handling
- I/O, errors
ms.workload:
- dotnet
- dotnetcore
ms.openlocfilehash: 51eb0e758f1ae8fb41c842ef9b32a9f8928af9ac
ms.sourcegitcommit: 7588136e355e10cbc2582f389c90c127363c02a5
ms.translationtype: HT
ms.contentlocale: ru-RU
ms.lasthandoff: 03/15/2020
ms.locfileid: "73120746"
---
# <a name="handling-io-errors-in-net"></a><span data-ttu-id="ef978-102">Обработка ошибок ввода-вывода в .NET</span><span class="sxs-lookup"><span data-stu-id="ef978-102">Handling I/O errors in .NET</span></span>

<span data-ttu-id="ef978-103">Помимо тех исключений, которые могут быть созданы в любом вызове метода (например, <xref:System.OutOfMemoryException> при высокой нагрузке на систему или <xref:System.NullReferenceException> при ошибке в программе), методы файловой системы .NET могут создавать следующие исключения:</span><span class="sxs-lookup"><span data-stu-id="ef978-103">In addition to the exceptions that can be thrown in any method call (such as an <xref:System.OutOfMemoryException> when a system is stressed or an <xref:System.NullReferenceException> due to programmer error), .NET file system methods can throw the following exceptions:</span></span>

- <span data-ttu-id="ef978-104"><xref:System.IO.IOException?displayProperty=nameWithType> — служит базовым классом для всех типов исключений <xref:System.IO>.</span><span class="sxs-lookup"><span data-stu-id="ef978-104"><xref:System.IO.IOException?displayProperty=nameWithType>, the base class of all <xref:System.IO> exception types.</span></span> <span data-ttu-id="ef978-105">Это исключение создается для ошибок, у которых код возврата из операционной системы не сопоставляется напрямую с другим типом исключения.</span><span class="sxs-lookup"><span data-stu-id="ef978-105">It is thrown for errors whose return codes from the operating system don't directly map to any other exception type.</span></span>
- <span data-ttu-id="ef978-106"><xref:System.IO.FileNotFoundException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="ef978-106"><xref:System.IO.FileNotFoundException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="ef978-107"><xref:System.IO.DirectoryNotFoundException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="ef978-107"><xref:System.IO.DirectoryNotFoundException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="ef978-108"><xref:System.IO.DriveNotFoundException??displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="ef978-108"><xref:System.IO.DriveNotFoundException??displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="ef978-109"><xref:System.IO.PathTooLongException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="ef978-109"><xref:System.IO.PathTooLongException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="ef978-110"><xref:System.OperationCanceledException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="ef978-110"><xref:System.OperationCanceledException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="ef978-111"><xref:System.UnauthorizedAccessException?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="ef978-111"><xref:System.UnauthorizedAccessException?displayProperty=nameWithType>.</span></span>
- <span data-ttu-id="ef978-112"><xref:System.ArgumentException?displayProperty=nameWithType> — создается для недопустимых символов пути на платформе .NET Framework, а также .NET Core 2.0 и предыдущих версиях.</span><span class="sxs-lookup"><span data-stu-id="ef978-112"><xref:System.ArgumentException?displayProperty=nameWithType>, which is thrown for invalid path characters on .NET Framework and on .NET Core 2.0 and previous versions.</span></span>
- <span data-ttu-id="ef978-113"><xref:System.NotSupportedException?displayProperty=nameWithType> — создается для недопустимых двоеточий в .NET Framework.</span><span class="sxs-lookup"><span data-stu-id="ef978-113"><xref:System.NotSupportedException?displayProperty=nameWithType>, which is thrown for invalid colons in .NET Framework.</span></span>
- <span data-ttu-id="ef978-114"><xref:System.Security.SecurityException?displayProperty=nameWithType> — создается для приложений в частичном доверии, которые не имеют необходимых разрешений (только на платформе .NET Framework).</span><span class="sxs-lookup"><span data-stu-id="ef978-114"><xref:System.Security.SecurityException?displayProperty=nameWithType>, which is thrown for applications running in limited trust that lack the necessary permissions on .NET Framework only.</span></span> <span data-ttu-id="ef978-115">На платформе .NET Framework по умолчанию используется полное доверие.</span><span class="sxs-lookup"><span data-stu-id="ef978-115">(Full trust is the default on .NET Framework.)</span></span>

## <a name="mapping-error-codes-to-exceptions"></a><span data-ttu-id="ef978-116">Сопоставление кодов ошибок с исключениями</span><span class="sxs-lookup"><span data-stu-id="ef978-116">Mapping error codes to exceptions</span></span>

<span data-ttu-id="ef978-117">Так как файловая система представляет собой ресурс операционной системы, методы ввода-вывода в .NET Core и .NET Framework служат оболочками для соответствующих вызовов операционной системы.</span><span class="sxs-lookup"><span data-stu-id="ef978-117">Because the file system is an operating system resource, I/O methods in both .NET Core and .NET Framework wrap calls to the underlying operating system.</span></span> <span data-ttu-id="ef978-118">Если в коде, выполняемом операционной системой, возникает ошибка ввода-вывода, операционная система возвращает сведения об ошибке в метод ввода-вывода .NET.</span><span class="sxs-lookup"><span data-stu-id="ef978-118">When an I/O error occurs in code executed by the operating system, the operating system returns error information to the .NET I/O method.</span></span> <span data-ttu-id="ef978-119">Затем этот метод преобразует сведения об ошибке, обычно представленные кодом ошибки, в соответствующий тип исключения .NET.</span><span class="sxs-lookup"><span data-stu-id="ef978-119">The method then translates the error information, typically in the form of an error code, into a .NET exception type.</span></span> <span data-ttu-id="ef978-120">В большинстве случаев код ошибки напрямую определяет нужный тип исключения. Метод не выполняет никакой дополнительной обработки в соответствии с контекстом вызова метода.</span><span class="sxs-lookup"><span data-stu-id="ef978-120">In most cases, it does this by directly translating the error code into its corresponding exception type; it does not perform any special mapping of the error based on the context of the method call.</span></span>

<span data-ttu-id="ef978-121">Например, при вызове метода в операционной системе Windows код ошибки `ERROR_FILE_NOT_FOUND` (или 0x02) преобразуется в исключение <xref:System.IO.FileNotFoundException>, а код ошибки `ERROR_PATH_NOT_FOUND` (или 0x03) — в <xref:System.IO.DirectoryNotFoundException>.</span><span class="sxs-lookup"><span data-stu-id="ef978-121">For example, on the Windows operating system, a method call that returns an error code of `ERROR_FILE_NOT_FOUND` (or 0x02) maps to a <xref:System.IO.FileNotFoundException>, and an error code of `ERROR_PATH_NOT_FOUND` (or 0x03) maps to a <xref:System.IO.DirectoryNotFoundException>.</span></span>

<span data-ttu-id="ef978-122">К сожалению, точные условия возникновения определенных кодов ошибок в операционной системе часто не документируются или документируются в недостаточном объеме.</span><span class="sxs-lookup"><span data-stu-id="ef978-122">However, the precise conditions under which the operating system returns particular error codes is often undocumented or poorly documented.</span></span> <span data-ttu-id="ef978-123">Это означает, что возможны непредвиденные исключения.</span><span class="sxs-lookup"><span data-stu-id="ef978-123">As a result, unexpected exceptions can occur.</span></span> <span data-ttu-id="ef978-124">Например, при работе с каталогом логично ожидать, что передача недопустимого пути в конструктор <xref:System.IO.DirectoryInfo.%23ctor%2A?displayProperty=nameWithType> приведет к созданию исключения <xref:System.IO.DirectoryNotFoundException>.</span><span class="sxs-lookup"><span data-stu-id="ef978-124">For example, because you are working with a directory rather than a file, you would expect that providing an invalid directory path to the <xref:System.IO.DirectoryInfo.%23ctor%2A?displayProperty=nameWithType> constructor throws a <xref:System.IO.DirectoryNotFoundException>.</span></span> <span data-ttu-id="ef978-125">Но в этой ситуации может создаваться и <xref:System.IO.FileNotFoundException>.</span><span class="sxs-lookup"><span data-stu-id="ef978-125">However, it may also throw a <xref:System.IO.FileNotFoundException>.</span></span>

## <a name="exception-handling-in-io-operations"></a><span data-ttu-id="ef978-126">Обработка исключений при операциях ввода-вывода</span><span class="sxs-lookup"><span data-stu-id="ef978-126">Exception handling in I/O operations</span></span>

<span data-ttu-id="ef978-127">По причине зависимости от операционной системы иногда идентичные условия (например, отсутствие указанного каталога) могут создавать в методах ввода-вывода любое исключение из класса ввода-вывода.</span><span class="sxs-lookup"><span data-stu-id="ef978-127">Because of this reliance on the operating system, identical exception conditions (such as the directory not found error in our example) can result in an I/O method throwing any one of the entire class of I/O exceptions.</span></span> <span data-ttu-id="ef978-128">Это означает, что при вызове интерфейсов API ввода-вывода ваш код должн быть готов обработать все такие исключения или большую их часть, как показано в следующей таблице:</span><span class="sxs-lookup"><span data-stu-id="ef978-128">This means that, when calling I/O APIs, your code should be prepared to handle most or all of these exceptions, as shown in the following table:</span></span>

| <span data-ttu-id="ef978-129">Тип исключения</span><span class="sxs-lookup"><span data-stu-id="ef978-129">Exception type</span></span> | <span data-ttu-id="ef978-130">.NET Core</span><span class="sxs-lookup"><span data-stu-id="ef978-130">.NET Core</span></span> | <span data-ttu-id="ef978-131">.NET Framework</span><span class="sxs-lookup"><span data-stu-id="ef978-131">.NET Framework</span></span> |
|---|---|---|
| <xref:System.IO.IOException> | <span data-ttu-id="ef978-132">Да</span><span class="sxs-lookup"><span data-stu-id="ef978-132">Yes</span></span> | <span data-ttu-id="ef978-133">Да</span><span class="sxs-lookup"><span data-stu-id="ef978-133">Yes</span></span> |
| <xref:System.IO.FileNotFoundException> | <span data-ttu-id="ef978-134">Да</span><span class="sxs-lookup"><span data-stu-id="ef978-134">Yes</span></span> | <span data-ttu-id="ef978-135">Да</span><span class="sxs-lookup"><span data-stu-id="ef978-135">Yes</span></span> |
| <xref:System.IO.DirectoryNotFoundException> | <span data-ttu-id="ef978-136">Да</span><span class="sxs-lookup"><span data-stu-id="ef978-136">Yes</span></span> | <span data-ttu-id="ef978-137">Да</span><span class="sxs-lookup"><span data-stu-id="ef978-137">Yes</span></span> |
| <xref:System.IO.DriveNotFoundException?> | <span data-ttu-id="ef978-138">Да</span><span class="sxs-lookup"><span data-stu-id="ef978-138">Yes</span></span> | <span data-ttu-id="ef978-139">Да</span><span class="sxs-lookup"><span data-stu-id="ef978-139">Yes</span></span> |
| <xref:System.IO.PathTooLongException> | <span data-ttu-id="ef978-140">Да</span><span class="sxs-lookup"><span data-stu-id="ef978-140">Yes</span></span> | <span data-ttu-id="ef978-141">Да</span><span class="sxs-lookup"><span data-stu-id="ef978-141">Yes</span></span> |
| <xref:System.OperationCanceledException> | <span data-ttu-id="ef978-142">Да</span><span class="sxs-lookup"><span data-stu-id="ef978-142">Yes</span></span> | <span data-ttu-id="ef978-143">Да</span><span class="sxs-lookup"><span data-stu-id="ef978-143">Yes</span></span> |
| <xref:System.UnauthorizedAccessException> | <span data-ttu-id="ef978-144">Да</span><span class="sxs-lookup"><span data-stu-id="ef978-144">Yes</span></span> | <span data-ttu-id="ef978-145">Да</span><span class="sxs-lookup"><span data-stu-id="ef978-145">Yes</span></span> |
| <xref:System.ArgumentException> | <span data-ttu-id="ef978-146">.NET Core 2.0 или более ранняя версия</span><span class="sxs-lookup"><span data-stu-id="ef978-146">.NET Core 2.0 and earlier</span></span>| <span data-ttu-id="ef978-147">Да</span><span class="sxs-lookup"><span data-stu-id="ef978-147">Yes</span></span> |
| <xref:System.NotSupportedException> | <span data-ttu-id="ef978-148">нет</span><span class="sxs-lookup"><span data-stu-id="ef978-148">No</span></span> | <span data-ttu-id="ef978-149">Да</span><span class="sxs-lookup"><span data-stu-id="ef978-149">Yes</span></span> |
| <xref:System.Security.SecurityException> | <span data-ttu-id="ef978-150">нет</span><span class="sxs-lookup"><span data-stu-id="ef978-150">No</span></span> | <span data-ttu-id="ef978-151">Только для ограниченного доверия</span><span class="sxs-lookup"><span data-stu-id="ef978-151">Limited trust only</span></span> |

## <a name="handling-ioexception"></a><span data-ttu-id="ef978-152">Обработка IOException</span><span class="sxs-lookup"><span data-stu-id="ef978-152">Handling IOException</span></span>

<span data-ttu-id="ef978-153"><xref:System.IO> является базовым классом для исключений в пространстве имен <xref:System.IO.IOException> и создается для любого кода ошибки, который не имеет сопоставления с определенным типом исключения.</span><span class="sxs-lookup"><span data-stu-id="ef978-153">As the base class for exceptions in the <xref:System.IO> namespace, <xref:System.IO.IOException> is also thrown for any error code that does not map to a predefined exception type.</span></span> <span data-ttu-id="ef978-154">Это означает, что оно может появиться в любой операции ввода-вывода.</span><span class="sxs-lookup"><span data-stu-id="ef978-154">This means that it can be thrown by any I/O operation.</span></span>

> [!IMPORTANT]
> <span data-ttu-id="ef978-155">Так как <xref:System.IO.IOException> является базовым классом для других типов исключений в пространстве имен <xref:System.IO>, его нужно обрабатывать в блоке `catch` после обработки других исключений, связанных с вводом-выводом.</span><span class="sxs-lookup"><span data-stu-id="ef978-155">Because <xref:System.IO.IOException> is the base class of the other exception types in the <xref:System.IO> namespace, you should handle in a `catch` block after you've handled the other I/O-related exceptions.</span></span>

<span data-ttu-id="ef978-156">Кроме того, в версии .NET Core 2.1 не применяется проверка правильности пути (например, отсутствия недопустимых символов в пути), и теперь среда выполнения создает исключение, сопоставленное с кодом ошибки операционной системы, а не результат проверки в собственном коде.</span><span class="sxs-lookup"><span data-stu-id="ef978-156">In addition, starting with .NET Core 2.1, validation checks for path correctness (for example, to ensure that invalid characters are not present in a path) have been removed, and the runtime throws an exception mapped from an operating system error code rather than from its own validation code.</span></span> <span data-ttu-id="ef978-157">В такой ситуации чаще всего создается исключение <xref:System.IO.IOException>, но вы можете столкнуться с любым другим типом исключений.</span><span class="sxs-lookup"><span data-stu-id="ef978-157">The most likely exception to be thrown in this case is an <xref:System.IO.IOException>, although any other exception type could also be thrown.</span></span>

<span data-ttu-id="ef978-158">Обратите внимание, что в коде обработки исключений <xref:System.IO.IOException> всегда нужно обрабатывать последним.</span><span class="sxs-lookup"><span data-stu-id="ef978-158">Note that, in your exception handling code, you should always handle the <xref:System.IO.IOException> last.</span></span> <span data-ttu-id="ef978-159">Иначе блоки catch для производных классов не проверяются, ведь это исключение является базовым классом для всех остальных.</span><span class="sxs-lookup"><span data-stu-id="ef978-159">Otherwise, because it is the base class of all other IO exceptions, the catch blocks of derived classes will not be evaluated.</span></span>

<span data-ttu-id="ef978-160">В случае с <xref:System.IO.IOException> дополнительные сведения об ошибке можно получить из свойства [IOException.HResult](xref:System.Exception.HResult).</span><span class="sxs-lookup"><span data-stu-id="ef978-160">In the case of an <xref:System.IO.IOException>, you can get additional error information from the [IOException.HResult](xref:System.Exception.HResult) property.</span></span> <span data-ttu-id="ef978-161">Чтобы преобразовать значение HResult в код ошибки Win32, отбросьте верхние 16 бит из 32-разрядного значения.</span><span class="sxs-lookup"><span data-stu-id="ef978-161">To convert the HResult value to a Win32 error code, you strip out the upper 16 bits of the 32-bit value.</span></span> <span data-ttu-id="ef978-162">В приведенной ниже таблице перечислены коды ошибок, которые могут быть заключены в <xref:System.IO.IOException>.</span><span class="sxs-lookup"><span data-stu-id="ef978-162">The following table lists error codes that may be wrapped in an <xref:System.IO.IOException>.</span></span>

| <span data-ttu-id="ef978-163">HResult</span><span class="sxs-lookup"><span data-stu-id="ef978-163">HResult</span></span> | <span data-ttu-id="ef978-164">Константа</span><span class="sxs-lookup"><span data-stu-id="ef978-164">Constant</span></span> | <span data-ttu-id="ef978-165">Описание:</span><span class="sxs-lookup"><span data-stu-id="ef978-165">Description</span></span> |
| --- | --- | --- |
| <span data-ttu-id="ef978-166">ERROR_SHARING_VIOLATION</span><span class="sxs-lookup"><span data-stu-id="ef978-166">ERROR_SHARING_VIOLATION</span></span> | <span data-ttu-id="ef978-167">32</span><span class="sxs-lookup"><span data-stu-id="ef978-167">32</span></span> | <span data-ttu-id="ef978-168">Отсутствует имя файла, или файл или каталог уже используется.</span><span class="sxs-lookup"><span data-stu-id="ef978-168">The file name is missing, or the file or directory is in use.</span></span> |
| <span data-ttu-id="ef978-169">ERROR_FILE_EXISTS</span><span class="sxs-lookup"><span data-stu-id="ef978-169">ERROR_FILE_EXISTS</span></span> | <span data-ttu-id="ef978-170">80</span><span class="sxs-lookup"><span data-stu-id="ef978-170">80</span></span> | <span data-ttu-id="ef978-171">Файл уже существует.</span><span class="sxs-lookup"><span data-stu-id="ef978-171">The file already exists.</span></span> |
| <span data-ttu-id="ef978-172">ERROR_INVALID_PARAMETER</span><span class="sxs-lookup"><span data-stu-id="ef978-172">ERROR_INVALID_PARAMETER</span></span> | <span data-ttu-id="ef978-173">87</span><span class="sxs-lookup"><span data-stu-id="ef978-173">87</span></span> | <span data-ttu-id="ef978-174">Методу передан недопустимый аргумент.</span><span class="sxs-lookup"><span data-stu-id="ef978-174">An argument supplied to the method is invalid.</span></span> |
| <span data-ttu-id="ef978-175">ERROR_ALREADY_EXISTS</span><span class="sxs-lookup"><span data-stu-id="ef978-175">ERROR_ALREADY_EXISTS</span></span> | <span data-ttu-id="ef978-176">183</span><span class="sxs-lookup"><span data-stu-id="ef978-176">183</span></span> | <span data-ttu-id="ef978-177">Файл или каталог уже существует.</span><span class="sxs-lookup"><span data-stu-id="ef978-177">The file or directory already exists.</span></span> |

<span data-ttu-id="ef978-178">Для обработки этих исключений можно применить предложение `When` в инструкции catch, как показано в приведенном ниже примере.</span><span class="sxs-lookup"><span data-stu-id="ef978-178">You can handle these using a `When` clause in a catch statement, as the following example shows.</span></span>

[!code-csharp[io-exception-handling](~/samples/snippets/standard/io/io-exceptions/cs/io-exceptions.cs)]
[!code-vb[io-exception-handling](~/samples/snippets/standard/io/io-exceptions/vb/io-exceptions.vb)]

## <a name="see-also"></a><span data-ttu-id="ef978-179">См. также раздел</span><span class="sxs-lookup"><span data-stu-id="ef978-179">See also</span></span>

- [<span data-ttu-id="ef978-180">Обработка и создание исключений в .NET</span><span class="sxs-lookup"><span data-stu-id="ef978-180">Handling and throwing exceptions in .NET</span></span>](../exceptions/index.md)
- [<span data-ttu-id="ef978-181">Обработка исключений (библиотека параллельных задач)</span><span class="sxs-lookup"><span data-stu-id="ef978-181">Exception handling (Task Parallel Library)</span></span>](../parallel-programming/exception-handling-task-parallel-library.md)
- [<span data-ttu-id="ef978-182">Лучшие методики обработки исключений</span><span class="sxs-lookup"><span data-stu-id="ef978-182">Best practices for exceptions</span></span>](../exceptions/best-practices-for-exceptions.md)
- [<span data-ttu-id="ef978-183">Практическое руководство. Использование определенных исключений в блоке catch</span><span class="sxs-lookup"><span data-stu-id="ef978-183">How to use specific exceptions in a catch block</span></span>](../exceptions/how-to-use-specific-exceptions-in-a-catch-block.md)
